apiVersion: apps/v1
kind: Deployment
metadata:
  name: decidim-k8s-app-deployment
spec:
  template:
    spec:
      containers:
        - name: decidim-k8s-app
          image: rg.fr-par.scw.cloud/decidim/osp-decidim:latest
          resources:
            requests:
              cpu: "900m"
              memory: "1250Mi"
            limits:
              cpu: "1024m"
              memory: "1500Mi"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - decidim-k8s-app
                topologyKey: topology.kubernetes.io/zone
