apiVersion: apps/v1
kind: Deployment
metadata:
  name: decidim-k8s-app-deployment
spec:
  selector:
    matchLabels:
      app: decidim-k8s-app
  template:
    metadata:
      labels:
        app: decidim-k8s-app
    spec:
      containers:
        - name: decidim-k8s-app
          image: rg.fr-par.scw.cloud/decidim/osp-decidim:latest
          command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
          resources:
            requests:
              cpu: "1024m"
              memory: "512Mi"
            limits:
              cpu: "2048m"
              memory: "1024Mi"
          ports:
            - containerPort: 3000
          livenessProbe:
            exec:
              command:
                - cat
                - tmp/pids/server.pid
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            exec:
              command:
                - cat
                - tmp/pids/server.pid
            initialDelaySeconds: 240
            failureThreshold: 30
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: decidim-k8s-config
            - secretRef:
                name: decidim-k8s-app-secrets
