apiVersion: apps/v1
kind: Deployment
metadata:
  name: decidim-k8s-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: decidim-k8s-app
  template:
    metadata:
      labels:
        app: decidim-k8s-app
    spec:
      containers:
        - name: decidim-k8s-app
          image: rg.fr-par.scw.cloud/decidim/osp-decidim:latest
          command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: decidim-k8s-config
            - secretRef:
                name: decidim-k8s-app-secrets
