apiVersion: v1
kind: ConfigMap
metadata:
  name: decidim-k8s-config
  labels:
    app: decidim-k8s-app
    sidekiq: decidim-k8s-sidekiq
data:
  RAILS_ENV: "production"
  RAILS_LOG_TO_STDOUT: "true"
  RAILS_SERVE_STATIC_FILES: "true"
