apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: osp-app-k8s-ing
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - hosts:
        - decidim.39854950-d62f-4660-a0b0-c350c02e2489.nodes.k8s.fr-par.scw.cloud
      secretName: decidim-tls
  rules:
    - host: decidim.39854950-d62f-4660-a0b0-c350c02e2489.nodes.k8s.fr-par.scw.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: decidim-k8s-app-load-balancer
                port:
                  number: 80
