apiVersion: apps/v1
kind: Deployment
metadata:
  name: decidim-k8s-sidekiq-deployment
spec:
  selector:
    matchLabels:
      sidekiq: decidim-k8s-sidekiq
  template:
    metadata:
      labels:
        sidekiq: decidim-k8s-sidekiq
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: decidim-k8s-sidekiq
          image: rg.fr-par.scw.cloud/decidim/osp-decidim:latest
          command: ["/usr/local/bundle/bin/bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "200m"
              memory: "1024Mi"
          ports:
            - containerPort: 3000
          livenessProbe:
            exec:
              command: ["./sidekiq_alive.sh"]
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            exec:
              command: ["./sidekiq_alive.sh"]
            initialDelaySeconds: 240
            failureThreshold: 30
            periodSeconds: 10
          lifecycle:
            preStop:
              exec:
                command: ["./sidekiq_quiet.sh"]
          envFrom:
            - configMapRef:
                name: decidim-k8s-config
            - secretRef:
                name: decidim-k8s-app-secrets
