:concurrency: 5
:queues:
  - default
  - mailers
  - newsletter
  - newsletters_opt_in
  - events
  - metrics
  - scheduled

:schedule:
  CalculateAllMetrics:
    cron: '0 0 0 * * *'
    class: CalculateAllMetricsJob
    queue: scheduled
  PreloadOpenData:
    cron: '0 0 1 * * *'
    class: PreloadOpenDataJob
    queue: scheduled
