:concurrency: 5
:queues:
  - default
  - mailers
  - newsletter
  - newsletters_opt_in
  - events
  - metrics
  - scheduled

:schedule:
  CalculateAllMetrics:
    every: ['24h', first_in: '5m']
    class: CalculateAllMetricsJob
    queue: scheduled
  PreloadOpenData:
    every: ['24h', first_in: '1m']
    class: PreloadOpenDataJob
    queue: scheduled
