apiVersion: apps/v1
kind: Deployment
metadata:
  name: decidim-k8s-sidekiq-deployment
spec:
  selector:
    matchLabels:
      sidekiq: decidim-k8s-sidekiq
  template:
    metadata:
      labels:
        sidekiq: decidim-k8s-sidekiq
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: decidim-k8s-sidekiq
          args: ["/usr/local/bundle/bin/bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
          ports:
            - containerPort: 3000
          livenessProbe:
            exec:
              command: ["./sidekiq_alive.sh"]
            failureThreshold: 3
            periodSeconds: 10
          startupProbe:
            exec:
              command: ["./sidekiq_alive.sh"]
            initialDelaySeconds: 60
            failureThreshold: 60
            periodSeconds: 10
          lifecycle:
            preStop:
              exec:
                command: ["./sidekiq_quiet.sh"]
          envFrom:
            - configMapRef:
                name: decidim-k8s-config
            - secretRef:
                name: decidim-k8s-app-secrets
