apiVersion: v1
kind: Pod
metadata:
  name: decidim-k8s-terminal-pod
spec:
  containers:
    - name: decidim-k8s-terminal
      command: ['sleep']
      args: ['infinity']
      envFrom:
        - configMapRef:
            name: decidim-k8s-config
        - secretRef:
            name: decidim-k8s-app-secrets
