---
name: Generate changelog
on:
  pull_request:
    branches:
      - "*"
jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Generate changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Wiki Changes
        uses: Andrew-Chen-Wang/github-wiki-action@v2
        env:
          # Make sure you have that / at the end. We use rsync
          # WIKI_DIR's default is wiki/
          WIKI_DIR: ./CHANGELOG.md
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MAIL: ${{ secrets.EMAIL }}
          GH_NAME: ${{ github.repository_owner }}
