---
name: Clean up

on:
  push:
    branches:
      - "feature/*"
      - develop
      - master

jobs:
  clean_up:
    runs-on: ubuntu-latest

    steps:
      - name: Set env
        run: echo "CACHE_TAG=${{ secrets.CACHE_REGISTRY }}/${GITHUB_REF}" >> $GITHUB_ENV
      - name: Login to registry
        run: |
          docker login ${{ secrets.CACHE_REGISTRY }} -u userdoesnotmatter -p ${{ secrets.TOKEN }}

      - name: Wait on cache build
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.sha }}
          check-name: build_cache_image
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30 # seconds

      - name: Wait on production Deploy
        if: github.ref == 'refs/heads/master'
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.sha }}
          check-name: deploy_production
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30 # seconds

      - name: Wait on production Deploy
        if: github.ref == 'refs/heads/develop'
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.sha }}
          check-name: deploy_staging
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30 # seconds

      - name: Removes old images
        run: |
          docker rmi ${{env.CACHE_TAG}}

