---
name: Clean up

on:
  push:
    branches:
      - "feature/*"
      - develop
      - master

jobs:
  clean_up:
    runs-on: ubuntu-latest

    steps:
      - name: Set env
        run: echo "CACHE_TAG=${{ secrets.CACHE_REGISTRY }}/${GITHUB_REF}" >> $GITHUB_ENV
      - name: 'Wait for status checks'
        id: waitforstatuschecks
        uses: "WyriHaximus/github-action-wait-for-status@v1.3.0"
        with:
          checkInterval: 60
      - uses: smartsquaregmbh/delete-old-packages@v0.2.0
        if: steps.waitforstatuschecks.outputs.status == 'success'
        with:
          names: |
            ${{env.CACHE_TAG}}

