---
name: Clean up

on:
  delete:
    branches:
      - "feature/*"
      - develop
      - master

jobs:
  clean_up:
    runs-on: ubuntu-latest

    steps:
      - name: Set env
        run: echo "CACHE_TAG=${{ secrets.CACHE_REGISTRY }}/${GITHUB_REF}" >> $GITHUB_ENV
      - name: Login to registry
        run: |
          docker login ${{ secrets.CACHE_REGISTRY }} -u userdoesnotmatter -p ${{ secrets.TOKEN }}
      - name: Removes old images
        run: |
          docker rmi ${{env.CACHE_TAG}}

