---
name: Deploy Image to registry

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to registry
        run: |
          docker login ${{ secrets.REGISTRY }} -u userdoesnotmatter -p ${{ secrets.TOKEN }}
      - name: Build image
        run: |
          docker build . --compress --tag ${{ secrets.TAG }}
      - name: Checks for modified kubeconfig
        uses: dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ github.ref }}
          filters: |
            src:
              - 'kubeconfig/app-deployment.yml'
              - 'kubeconfig/sidekiq-deployment.yml'
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@master
        with:
          ref: master # can be commit SHA or tag too
          check-name: Tests # name of the existing check - omit to wait for all checks
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30 # seconds
      - name: Push Image
        run: |
          docker push ${{ secrets.TAG }}
      - name: delete old migration job
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: delete job decidim-k8s-migration-job --ignore-not-found
      - name: Run migration
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f kubeconfig/migration-job.yaml
      - name: Apply configuration changes
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f kubeconfig
      - name: Run rolling update
        if: steps.changes.outputs.src == 'false'
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout restart deployment
