---
name: Deploy Image to registry

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to registry
        run: |
          docker login ${{ secrets.REGISTRY }} -u userdoesnotmatter -p ${{ secrets.TOKEN }}
      - name: Build image
        run: |
          docker build . --compress --tag ${{ secrets.TAG }}
      - name: Push Image
        run: |
          docker push ${{ secrets.TAG }}
      - name: Run migration
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: exec -it decidim-k8s-terminal-pod -- bundle exec rails db:migrate
      - name: Run rolling update
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout restart deployment
