name: [CI] Main

on:
  workflow_run:
    workflows:
      - Tests
      - Lint
    branches:
      - develop
      - master
    types:
      - completed

env:
  CI: "true"

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    if: "!startsWith(github.head_ref, 'chore/l10n')"
    steps:
      - name: Check
        run: exit 0

