---
name: Prepare release
on:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    steps:
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 1
          format: 'YYYY-MM-DD-HH-mm-ss'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: develop
          commit-message: Bump Gemfile.lock and install migrations
          branch: "release/${{ steps.time.outputs.time }}"
          title: 'Release #major'
          body: |
            🚀 New release available 🚀
