---
name: Deploy Image to production

on:
  push:
    branches:
      - wip/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build . --compress --tag ${{ secrets.TAG }} --cache-from ${{ secrets.TAG }}
